export const PLAIN_DISTANCE_ALGORITHM = 'PLAIN_DISTANCE_ALGORITHM';
export const DECISIVE_FUNCTION_ALGORITHM = 'DECISIVE_FUNCTION_ALGORITHM';
export const SEPARATING_FUNCTION_ALGORITHM = 'SEPARATING_FUNCTION_ALGORITHM';
